# Generated by Django 4.2.1 on 2023-05-27 05:29

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):
    dependencies = [
        ("word", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="course",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="word.course"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
            ),
        ),
    ]
