# Generated by Django 4.2.1 on 2023-06-03 19:00

import datetime
from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):
    dependencies = [
        ("word", "0007_alter_course_id_alter_flashcard_id_userlearningdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("review_date", models.DateTimeField(default=datetime.datetime.now)),
                ("retention_rate", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="retention_rates",
            field=models.ManyToManyField(to="word.retentionrate"),
        ),
    ]
