# Generated by Django 4.2.1 on 2023-06-04 10:45

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):
    dependencies = [
        ("word", "0013_userlearningdata_course_alter_course_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlearningdata",
            name="retention_rates",
        ),
        migrations.AddField(
            model_name="userlearningdata",
            name="forgetting_curve",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
            ),
        ),
    ]
