# Generated by Django 4.2.2 on 2023-07-02 11:22

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):
    dependencies = [
        ("word", "0016_alter_course_id_alter_flashcard_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlearningdata",
            name="forgetting_curve",
        ),
        migrations.AddField(
            model_name="userlearningdata",
            name="retention_rates",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="userlearningdata",
            name="review_dates",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
            ),
        ),
    ]
