# Generated by Django 4.2.2 on 2023-07-22 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("word", "0018_course_user_alter_course_id_alter_flashcard_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="CourseAccessHistory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="word.course")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_index", models.PositiveIntegerField(default=0)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="word.course")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "course")},
            },
        ),
    ]
